cask "discord"
cask "docker"
cask "elgato-stream-deck"
cask "google-chrome"
cask "gpg-suite"
cask "homerow"
cask "iterm2"
cask "rectangle"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "zoom"

brew "hstr"